#include "gba.h"
#include "logic.h"
#include "graphics.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
#include "images/title.h"
#include "images/instructions.h"
#include "images/winner.h"
#include "images/loser.h"
#include <stdio.h>
#include <stdlib.h>

// AppState enum definition
typedef enum {
    // TA-TODO: Add any additional states you need for your app.
    START,
    START_NODRAW,
    INSTRUCTIONS,
    INSTRUCTIONS_NODRAW,
    APP_INIT,
    APP,
    WINNER,
    LOSER,
    APP_EXIT_NODRAW,
} GBAState;

int main(void) {
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    // We store the "previous" and "current" states.
    AppState currentAppState, nextAppState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while(1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;

        // TA-TODO: Manipulate the state machine below as needed.
        switch(state) {
        case START:
            // Wait for VBlank
            waitForVBlank();

            drawFullScreenImageDMA(title);
            char testString[] = "Press A to Start";
            drawCenteredString(0, 130, 240, 20, testString, RED);
            state = START_NODRAW;
            break;
        case START_NODRAW:
            // TA-TODO: Check for a button press here to start the app.
            // Start the app by switching the state to APP_INIT.
            if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                state = INSTRUCTIONS;  
            }
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;  
            }
            break;
        case INSTRUCTIONS:
            drawFullScreenImageDMA(instructions);
            drawCenteredString(0, 130, 240, 30, testString, RED);
            state = INSTRUCTIONS_NODRAW;
            break;
        case INSTRUCTIONS_NODRAW:
            if (KEY_JUST_PRESSED(BUTTON_A, currentButtons, previousButtons)) {
                state = APP_INIT;  
            }
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;  
            }
            
            break;
        case APP_INIT:
            // Initialize the app. Switch to the APP state.
            initializeAppState(&currentAppState);
            // Draw the initial state of the app
            fullDrawAppState(&currentAppState);

            state = APP;
            break;
        case APP:
            // Process the app for one frame, store the next state
            nextAppState = processAppState(&currentAppState, previousButtons, currentButtons);

            // Wait for VBlank before we do any drawing.

            waitForVBlank();
            if (nextAppState.timer == 0) {
                nextAppState.gameOver = 1;
            }
            // if (currentAppState.playerBlockIndex != nextAppState.playerBlockIndex) {
            // Undraw the previous state
            undrawAppState(&currentAppState);
            // Draw the current state
            drawAppState(&nextAppState);
            if (vBlankCounter % 60 == 0) {
                drawRectDMA(0,YOFFSET + 10, XOFFSET, 10,BLACK);
                nextAppState.timer = nextAppState.timer - 1;
            }
            drawRectDMA(0,YOFFSET + 10, XOFFSET, 10, LIGHTBLUE);
            char timeLeft[5];
            sprintf(timeLeft, "%d", nextAppState.timer);
            drawCenteredString(0,YOFFSET + 10, XOFFSET, 10,timeLeft, RED);
            drawRectDMA(XOFFSET + MAZEWIDTH,YOFFSET + 20, XOFFSET, 10, LIGHTBLUE);
            char acornsLeft[5];
            sprintf(acornsLeft, "%d", nextAppState.cornersRemaining);
            drawCenteredString(XOFFSET + MAZEWIDTH,YOFFSET + 20, XOFFSET, 10,acornsLeft, RED);
            

            // Now set the current state as the next state for the next iter.
            currentAppState = nextAppState;

            // Check if the app is exiting. If it is, then go to the exit state.
            if (nextAppState.gameOver) state = LOSER;
            if (nextAppState.playerBlockIndex == nextAppState.endBlockIndex) {
                state = WINNER;
            }
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;  
            }
            break;
        case WINNER:
            waitForVBlank();
            fillScreenDMA(LIGHTBLUE);
            drawFullScreenImageDMA(winner);
            state = APP_EXIT_NODRAW;
            break;
        case LOSER:
            // Wait for VBlank
            waitForVBlank();

            // TA-TODO: Draw the exit / gameover screen
            drawFullScreenImageDMA(loser);

            state = APP_EXIT_NODRAW;
            break;
        case APP_EXIT_NODRAW:
            if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
                state = START;  
            }

            break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
